config/routes.rb
Rails.application.routes.draw do

  get '/about', to: 'about#index', as: 'about'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  root to: 'products#index'

  resources :products, only: [:index, :show]
  resources :categories, only: [:show]
  resources :users, only: [:new, :create]
  resources :sessions, only: [:new, :create, :destroy]

  resource :cart, only: [:show] do
    post   :add_item
    post   :remove_item
  end

  resources :orders, only: [:create, :show]

  namespace :admin do
    root to: 'dashboard#show'
    resources :products, except: [:edit, :update, :show]
    resources :categories, only: [:index, :new, :create]
  end

end

app/models/category.rb
class Category < ApplicationRecord
  
  validates :name, presence: true

  has_many :products

end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to admin_categories_path, notice: 'Category created successfully.'
    else
      render :new
    end
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate, if: :admin_namespace?

  def show
    @category = Category.find(params[:id])
    @products = @category.products.order(created_at: :desc)
  end

end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/views/admin/categories/_category.html.erb
<tr>
  <td>
    <h4><%= category.name %></h4>
  </td>
  <td>
    <%= category.created_at.strftime("%Y-%m-%d %H:%M") %>
  </td>
</tr>

app/views/admin/categories/index.html.erb
<section class="admin-categories-index">
  <header class="page-header">
    <h1>Admin &raquo; Categories</h1>
  </header>

  <div class="well">
    <%= link_to '+ New Category', new_admin_category_path, class: 'btn btn-info' %>
  </div>

  <div class="panel panel-default categories">
    <table class="table table-bordered">
      <thead>
        <tr>
          <th>Category</th>
          <th>Date Created</th>                 
        </tr>
      </thead>
      <tbody>
        <%= render @categories %>
      </tbody>
    </table>
  </div>
</section>

app/views/admin/categories/new.html.erb
<section class="admin-categories-new">

  <header class="page-header">
    <h1>Admin &raquo; New Category</h1>
  </header>

  <div class="well">
    <%= link_to 'All Categories', admin_categories_path, class: 'btn btn-info' %>
  </div>

  <div class="row">
    <div class="col-sm-6 col-sm-offset-1">
      <%= form_for [:admin, @category] do |form| %>

        <% if form.object.errors.any? %>
          <div class="alert alert-danger">
            <strong>The following errors prevented saving:</strong>
            <ul>
              <% form.object.errors.full_messages.each do |error| %>
                <li><%= error %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

        <div class="form-group">
          <%= form.label :name %>
          <%= form.text_field :name, class: 'form-control' %>
        </div>

        <%= form.submit 'Create Category', class: 'btn btn-primary' %>
      <% end %>
    </div>
  </div>

</section>